package com.prologic.laughinggoat.model.shipping

data class Settings(
    val advanced: Items,
    val availability: Items,
    val class_cost_60: Items,
    val class_costs: Items,
    val cost: Items,
    val distance_calculation: Items,
    val excl_product: Items,
    val excl_product_cat: Items,
    val excl_product_tag: Items,
    val free_shipping_min_amount: Items,
    val free_shipping_products: Items,
    val incl_product: Items,
    val incl_product_cat: Items,
    val incl_product_tag: Items,
    val limit_calc: Items,
    val max_cost: Items,
    val max_cost_limit: Items,
    val max_distance: Items,
    val max_qty: Items,
    val max_volume: Items,
    val max_weight: Items,
    val min_cost: Items,
    val min_cost_limit: Items,
    val min_distance: Items,
    val min_qty: Items,
    val min_volume: Items,
    val min_weight: Items,
    val no_class_cost: Items,
    val require_type: Items,
    val return_url: Items,
    val tax_status: Items,
    val title: Items,
    val type: Items
)